<?php
    
    include('db.php');

    // $query = "SELECT * FROM user";
    // $result = mysql_query($query) or die("Query failed");
    $result = mysql_query("SELECT * FROM user" );
    // $rec = mysql_fetch_array($result); 

?>

<!DOCTYPE html>
<html class="lockscreen">
    <head>
        <meta charset="UTF-8">
        <title>Handel Marketing</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <!-- bootstrap 3.0.2 -->
        <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <!-- font Awesome -->
        <link href="css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <!-- Theme style -->
        <link href="css/AdminLTE.css" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        

    </head>
    <body>
        <!-- Automatic element centering using js -->
        <div class="center"> 
            <br>
            <center><h1>Handel Marketing Sdn Bhd</h1></center><br>

            <div class="headline text-center" id="time">
                <!-- Time auto generated by js -->
            </div><!-- /.headline -->
            
            <!-- User name -->
            
            
            <center><div class="alert alert-info" role="alert"><font size="4"><b>Please choose user</b></font></div></center><br><br>
            <!-- START LOCK SCREEN ITEM -->

            <?php 
          while ($rec = mysql_fetch_array($result)) { ?>

            <div class="lockscreen-item">
                <!-- lockscreen image -->
                <div class="lockscreen-image">
                    <?php 

                    if($rec['gender']=="Male"){?> 
                        <img src="img/male.png" class="img-circle" alt="user image"/> 
                    <?php } 
                    else if($rec['gender']=="Female"){ ?>
                        <img src="img/female.png" class="img-circle" alt="user image"/> 
                    <?php } 
                    else {?>
                        <img src="img/avatar5.png" class="img-circle" alt="user image"/> 
                    <?php }?>
                </div>
                <!-- /.lockscreen-image -->

                <!-- lockscreen credentials (contains the form) -->
                <div class="lockscreen-credentials">   

                    <div class="input-group">
                        <div class="lockscreen-name"><a href="login.php?Name=<?php echo $rec['name']; ?>&error=false"><?php echo $rec['name']; ?></a></div>
                    </div>
                </div><!-- /.lockscreen credentials -->

            </div><br><br><br>

          <?php } ?>


            <!-- /.lockscreen-item -->

            <!-- <div class="lockscreen-link">
                <a href="login.html">Or sign in as a different user</a>
            </div> -->            
        </div><!-- /.center -->

        <!-- jQuery 2.0.2 -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="js/bootstrap.min.js" type="text/javascript"></script>

        <!-- page script -->
        <script type="text/javascript">
            $(function() {
                startTime();
                $(".center").center();
                $(window).resize(function() {
                    $(".center").center();
                });
            });

            /*  */
            function startTime()
            {
                var today = new Date();
                var h = today.getHours();
                var m = today.getMinutes();
                var s = today.getSeconds();

                // add a zero in front of numbers<10
                m = checkTime(m);
                s = checkTime(s);

                //Check for PM and AM
                var day_or_night = (h > 11) ? "PM" : "AM";

                //Convert to 12 hours system
                if (h > 12)
                    h -= 12;

                //Add time to the headline and update every 500 milliseconds
                $('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
                setTimeout(function() {
                    startTime()
                }, 500);
            }

            function checkTime(i)
            {
                if (i < 10)
                {
                    i = "0" + i;
                }
                return i;
            }

            /* CENTER ELEMENTS IN THE SCREEN */
            jQuery.fn.center = function() {
                this.css("position", "absolute");
                this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
                        $(window).scrollTop()) - 30 + "px");
                this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
                        $(window).scrollLeft()) + "px");
                return this;
            }
        </script>
    </body>
</html>